---

- name: Add Elastic gpg key
  become: yes
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Logstash repo
  become: yes
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ sansible_logstash_family }}/apt stable main"
    state: present

- name: Install Logstash
  become: yes
  apt:
    name: "logstash={{ sansible_logstash_version }}"
    state: installed
  notify: restart logstash
